blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question
    url: https://github.com/Ironchip-Security/bug-tracker/discussions/new?category=q-a
    about: Ask and discuss questions with ours community members

  - name: ğŸ“š Documentation
    url: https://helpcenter.ironchip.com/userdocumentation/
    about: Check the documentation for help
